swagger: "2.0"
info:
  version: "1.0.0"
  title: "Controlador de API de Usuarios"
  description: "Controlador que contiene las funciones para manejar las operaciones relacionadas con usuarios."
paths:
  /usuarios:
    get:
      summary: Obtener todos los users
      responses:
        200:
          description: Lista de usuarios
        500:
          description: Error interno del servidor

      # responses:
        201:
          description: Usuario registrado exitosamente
        401:
          description: No autorizado
  /usuarios/delete:
    delete:
      summary: Eliminar un usuario
      parameters:
        - name: body
          in: body
          description: Datos del usuario a eliminar
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: Correo electrónico del usuario a eliminar
                example: usuario@example.com
      responses:
        201:
          description: Usuario eliminado exitosamente
  /usuarios/premium:
    put:
      summary: Actualizar el estado premium del usuario
      responses:
        201:
          description: Estado premium del usuario actualizado exitosamente
  /usuarios/restablecer:
    post:
      summary: Restablecer contraseña de usuario
      parameters:
        - name: body
          in: body
          description: Datos del usuario para restablecer contraseña
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: Correo electrónico del usuario para restablecer contraseña
                example: usuario@example.com
      responses:
        200:
          description: Token de recuperación enviado exitosamente
  /usuarios/restablecer/nueva:
    put:
      summary: Restablecer nueva contraseña de usuario
      parameters:
        - name: body
          in: body
          description: Nueva contraseña del usuario
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
                description: Nueva contraseña del usuario
                example: nuevacontraseña123
      responses:
        201:
          description: Contraseña restablecida exitosamente
